# Generated by Django 6.0.5 on 2026-06-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI ID/Intent'), ('QR', 'QR Code Scanner'), ('COD', 'Cash On Delivery'), ('B2B', 'B2B Wholesale / Export')], max_length=20),
        ),
    ]
