services:
  - type: web
    name: bhavani-cashews
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --log-file -"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "bhavani-cashews.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        sync: false  # Loaded securely via Render Dashboard Env Variables (Supabase Pooler)
      - key: CLOUDINARY_CLOUD_NAME
        value: "ddq299bju"
      - key: CLOUDINARY_API_KEY
        value: "599189223837844"
      - key: CLOUDINARY_API_SECRET
        sync: false  # Loaded securely via Render Dashboard Env Variables
      - key: MERCHANT_UPI_ID
        value: "indranilsawant07@okaxis"
      - key: MERCHANT_NAME
        value: "Bhavani Cashews"
