/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./**/templates/**/*.html",
    "./new_templates/**/*.html",
    "./static/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e8ec",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c6c7c0",
        "primary-fixed": "#e4e2de",
        "surface-container": "#eceef2",
        "primary-container": "#fdfbf7",
        "on-secondary-fixed-variant": "#4f4538",
        "on-primary-fixed": "#1b1c1a",
        "secondary-container": "#efe0cd",
        "surface-container-highest": "#e0e2e6",
        "on-error": "#ffffff",
        "surface": "#f7f9fd",
        "inverse-primary": "#c8c6c3",
        "surface-variant": "#e0e2e6",
        "secondary-fixed-dim": "#d2c4b2",
        "error": "#ba1a1a",
        "surface-dim": "#d8dade",
        "on-primary-container": "#747471",
        "inverse-on-surface": "#eff1f5",
        "on-secondary-container": "#6d6354",
        "surface-container-low": "#f2f4f8",
        "secondary": "#675d4e",
        "on-primary-fixed-variant": "#474744",
        "on-tertiary-container": "#866e63",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#705a4f",
        "secondary-fixed": "#efe0cd",
        "inverse-surface": "#2d3134",
        "tertiary-fixed": "#fbdcce",
        "on-tertiary-fixed": "#281810",
        "on-surface": "#191c1f",
        "tertiary-fixed-dim": "#dec1b3",
        "on-surface-variant": "#454742",
        "surface-tint": "#5e5e5c",
        "on-error-container": "#93000a",
        "primary": "#5e5e5c",
        "error-container": "#ffdad6",
        "on-background": "#191c1f",
        "tertiary-container": "#fffaf9",
        "on-secondary-fixed": "#221a0f",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#574238",
        "background": "#f7f9fd",
        "on-primary": "#ffffff",
        "outline": "#767872",
        "primary-fixed-dim": "#c8c6c3",
        "surface-bright": "#f7f9fd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "label-caps": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"]
      },
      fontSize: {
        "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-lg-mobile": ["40px", {"lineHeight": "1.2", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
