# Generated by Django 6.0.5 on 2026-05-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashewGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('W180', 'W180'), ('W210', 'W210'), ('W240', 'W240'), ('W320', 'W320'), ('W400', 'W400'), ('Splits', 'Splits'), ('JK', 'JK'), ('K', 'K'), ('LWP', 'LWP'), ('SWP', 'SWP'), ('SP', 'SP'), ('SW', 'SW'), ('Kani', 'Kani'), ('NW', 'NW')], max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cashew_grades/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.cashewgrade'),
        ),
    ]
