# Generated by Django 6.0.5 on 2026-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cashewgrade_product_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_export_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, help_text='Origin location of cashews', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_size',
            field=models.CharField(choices=[('250g', '250g'), ('500g', '500g'), ('1kg', '1kg'), ('5kg', '5kg'), ('10kg', '10kg')], default='1kg', max_length=20),
        ),
    ]
