# Generated by Django 6.0.5 on 2026-06-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount_price_product_is_export_quality_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'is_featured', '-created_at'], name='products_pr_is_avai_3a747d_idx'),
        ),
    ]
