# Generated by Django 6.0.5 on 2026-06-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_products_pr_is_avai_3a747d_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', '-created_at'], name='products_pr_is_avai_8299d1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available', '-created_at'], name='products_pr_categor_e2a61c_idx'),
        ),
    ]
